"""account sharing

Revision ID: 0005_account_sharing
Revises: 0004_rename_score_column
Create Date: 2026-08-21 00:31:51.010597

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_account_sharing'
down_revision: Union[str, None] = '0004_rename_score_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_invites_owner_id'), 'account_invites', ['owner_id'], unique=False)
    op.create_index(op.f('ix_account_invites_token'), 'account_invites', ['token'], unique=True)
    op.create_table('account_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'member_id', name='uq_account_member')
    )
    op.create_index(op.f('ix_account_memberships_member_id'), 'account_memberships', ['member_id'], unique=False)
    op.create_index(op.f('ix_account_memberships_owner_id'), 'account_memberships', ['owner_id'], unique=False)
    op.create_table('account_public_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_public_shares_owner_id'), 'account_public_shares', ['owner_id'], unique=True)
    op.create_index(op.f('ix_account_public_shares_token'), 'account_public_shares', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_public_shares_token'), table_name='account_public_shares')
    op.drop_index(op.f('ix_account_public_shares_owner_id'), table_name='account_public_shares')
    op.drop_table('account_public_shares')
    op.drop_index(op.f('ix_account_memberships_owner_id'), table_name='account_memberships')
    op.drop_index(op.f('ix_account_memberships_member_id'), table_name='account_memberships')
    op.drop_table('account_memberships')
    op.drop_index(op.f('ix_account_invites_token'), table_name='account_invites')
    op.drop_index(op.f('ix_account_invites_owner_id'), table_name='account_invites')
    op.drop_table('account_invites')
    # ### end Alembic commands ###
