"""home feature

Revision ID: 0007_home_feature
Revises: 0006_oauth_identities
Create Date: 2026-08-21 01:06:13.752366

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007_home_feature'
down_revision: Union[str, None] = '0006_oauth_identities'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_features',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('feature_type', sa.String(length=20), server_default='default', nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=True),
    sa.Column('artist_id', sa.UUID(), nullable=True),
    sa.Column('custom_image_url', sa.Text(), nullable=True),
    sa.Column('custom_title', sa.String(length=200), nullable=True),
    sa.Column('custom_subtitle', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_features')
    # ### end Alembic commands ###
