"""collection value tracking

Revision ID: 0009_value_tracking
Revises: 0008_social_layer
Create Date: 2026-08-21 02:15:18.839256

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0009_value_tracking'
down_revision: Union[str, None] = '0008_social_layer'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_value_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('valued_count', sa.Integer(), nullable=False),
    sa.Column('holdings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_value_snapshots_captured_at'), 'collection_value_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_collection_value_snapshots_user_id'), 'collection_value_snapshots', ['user_id'], unique=False)
    op.create_table('release_valuations',
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('release_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_valuations')
    op.drop_index(op.f('ix_collection_value_snapshots_user_id'), table_name='collection_value_snapshots')
    op.drop_index(op.f('ix_collection_value_snapshots_captured_at'), table_name='collection_value_snapshots')
    op.drop_table('collection_value_snapshots')
    # ### end Alembic commands ###
